import type { Lead } from "@/lib/types/database";

const AUTO_WHATSAPP_NOTE_PATTERNS = [
  /^WhatsApp loan type:/i,
  /^Personal loan \(WhatsApp\):/i,
  /^Credit card outstanding \(WhatsApp\):/i,
  /^Early WhatsApp contact/i,
] as const;

export function isAutoGeneratedWhatsAppNotes(notes: string): boolean {
  const lines = notes
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);

  if (!lines.length) return false;

  return lines.every((line) =>
    AUTO_WHATSAPP_NOTE_PATTERNS.some((pattern) => pattern.test(line))
  );
}

export function getDisplayLeadNotes(lead: Lead): string | null {
  const notes = lead.notes?.trim();
  if (!notes) return null;

  if (lead.source === "whatsapp" && isAutoGeneratedWhatsAppNotes(notes)) {
    return null;
  }

  return notes;
}

export type LeadAdditionalInfo = {
  notes: string | null;
  assignmentComment: string | null;
};

export function getLeadAdditionalInfo(lead: Lead): LeadAdditionalInfo {
  return {
    notes: getDisplayLeadNotes(lead),
    assignmentComment: lead.assignment_comment?.trim() || null,
  };
}

export function hasLeadAdditionalInfo(info: LeadAdditionalInfo): boolean {
  return Boolean(info.notes || info.assignmentComment);
}

export function resolveWhatsAppLeadNotes(
  fieldsNotes: string | null,
  existingNotes: string | null | undefined
): string | null {
  if (fieldsNotes?.trim()) return fieldsNotes.trim();

  const existing = existingNotes?.trim();
  if (existing && !isAutoGeneratedWhatsAppNotes(existing)) {
    return existing;
  }

  return null;
}
